
version: "3"
services:

  authorizationserver:
    image: ccesdev.com/authserver:snapshot-0.18
    ports:
        - "8080:8080"
    environment:
        - SPRING_PROFILES_ACTIVE=e2e
        - SPRING_DATASOURCE_URL=jdbc:mysql://auth_store/users?useUnicode=yes&characterEncoding=UTF-8
        - SPRING_DATASOURCE_USERNAME=authorizationuser
        - SPRING_DATASOURCE_PASSWORD=mXzaTT2x2mvUhRwD
        - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver


  event_store:
      image:  ccesdev.com/mysql
      container_name: event_store
      ports:
          - 3306:3306
      environment:
          - MYSQL_ROOT_PASSWORD=rootpassword
          - MYSQL_USER=mysqluser
          - MYSQL_PASSWORD=mysqlpw

  zookeeper:
      image: eventuateio/eventuateio-local-zookeeper:0.13.0
      container_name: zookeeper
      ports:
          - 2181:2181
          - 2888:2888
          - 3888:3888
  kafka:
      image: eventuateio/eventuateio-local-kafka:0.13.0
      container_name: kafka
      ports:
          - 9092:9092
      links:
          - zookeeper
      environment:
          - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
          - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
          - ZOOKEEPER_SERVERS=zookeeper:2181
